###################
# imported images #
###################

FROM dlang-dockerized/llvm:7-trixie AS llvm-imported

###############
# build stage #
###############

FROM docker.io/debian:trixie-slim AS build-stage-1

WORKDIR /opt/build

# Install dependencies

## Install common system-tools

### Install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN apt-get -y install \
	build-essential \
	curl \
	git \
	libcurl4-openssl-dev
RUN rm -rf /var/lib/apt/lists/*

## Install LDC build deps
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
	cmake \
	ninja-build \
	libconfig-dev \
	libtinfo-dev \
	python3
RUN rm -rf /var/lib/apt/lists/*

# Copy prebuilt LLVM from dlang-dockerized/llvm
COPY --from=llvm-imported /opt/llvm/ /opt/llvm/

# Download LDC sources

### Download LDC source
RUN curl -fLsSo ldc.tar.gz \
	"https://github.com/ldc-developers/ldc/archive/refs/heads/ltsmaster.tar.gz"

### Download Phobos source
RUN curl -fLsSo phobos.tar.gz \
	"https://github.com/ldc-developers/phobos/archive/refs/heads/ldc-ltsmaster.tar.gz"

### Download separate druntime source (old repo layout)
RUN curl -fLsSo druntime.tar.gz \
	"https://github.com/ldc-developers/druntime/archive/refs/heads/ldc-ltsmaster.tar.gz"


# Build and install LDC

## Build LDC

### Unpack sources
RUN mkdir ldc-source ldc-build
RUN tar -xf ldc.tar.gz -C ldc-source --strip-components=1
RUN tar -xf phobos.tar.gz -C ldc-source/runtime/phobos --strip-components=1
RUN tar -xf druntime.tar.gz -C ldc-source/runtime/druntime --strip-components=1


### Build
RUN cmake \
	-S ldc-source \
	-B ldc-build \
	-G Ninja \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/opt/ldc \
	-DLLVM_ROOT_DIR=/opt/llvm \
	-DCMAKE_C_COMPILER=gcc \
	-DCMAKE_CXX_COMPILER=g++ \
	-DCMAKE_ASM_COMPILER=gcc
RUN cmake --build ldc-build

### Install
RUN cmake --install ldc-build
ENV DMD=/opt/ldc/bin/ldmd2

# Self-test
COPY ./resources/helloworld.d /opt/helloworld.d
RUN /opt/ldc/bin/ldmd2 -run /opt/helloworld.d
RUN rm /opt/helloworld.d

## Make DUB

### -- Without DUB --

## Make D Tools

### Download D Tools source
RUN curl -fLsSo d-tools.tar.gz "https://github.com/dlang/tools/archive/refs/tags/v2.068.2.tar.gz"
### Build D Tools
RUN mkdir -p d-tools
RUN tar -xf d-tools.tar.gz -C d-tools --strip-components=1
RUN make -C d-tools \
-f posix.mak \
	DMD=$DMD \
	all
################
# export stage #
################

FROM docker.io/debian:trixie-slim AS export-stage

## Prepare runtime-environment

### Install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
	libconfig-dev \
	build-essential \
	curl \
	libcurl4-openssl-dev
RUN rm -rf /var/lib/apt/lists/*
COPY --from=llvm-imported /opt/llvm/bin /opt/llvm/bin

RUN ln -s /opt/llvm/bin/clang /usr/local/bin/clang
RUN ln -s /opt/llvm/bin/clang /usr/local/bin/clang++
RUN ln -s /opt/llvm/bin/llc /usr/local/bin/llc



COPY --from=build-stage-1 /opt/ldc /opt/ldc

RUN ln -s /opt/ldc/bin/ldc2 /usr/local/bin/ldc2
RUN ln -s /opt/ldc/bin/ldmd2 /usr/local/bin/ldmd2
RUN ln -s /opt/ldc/bin/ldmd2 /usr/local/bin/dmd
ENV DMD=/usr/local/bin/ldmd2

## Install D Tools
COPY --from=build-stage-1 /opt/build/d-tools/generated/linux/64/ddemangle /usr/local/bin/ddemangle
COPY --from=build-stage-1 /opt/build/d-tools/generated/linux/64/dustmite /usr/local/bin/dustmite
COPY --from=build-stage-1 /opt/build/d-tools/generated/linux/64/rdmd /usr/local/bin/rdmd
# Self-test
COPY ./resources/helloworld.d /opt/helloworld.d
RUN /opt/ldc/bin/ldmd2 -run /opt/helloworld.d
RUN rm /opt/helloworld.d


## Install D Tools
COPY --from=build-stage-1 /opt/build/d-tools/generated/linux/64/ddemangle /usr/local/bin/ddemangle
COPY --from=build-stage-1 /opt/build/d-tools/generated/linux/64/dustmite /usr/local/bin/dustmite
COPY --from=build-stage-1 /opt/build/d-tools/generated/linux/64/rdmd /usr/local/bin/rdmd
COPY ./resources/scripts/entrypoint-ldc.sh /usr/local/bin/entrypoint

ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
CMD [ "/usr/local/bin/ldc2" ]
