###################
# imported images #
###################

FROM dlang-dockerized/llvm:20.1-trixie AS llvm-imported
FROM dlang-dockerized/ldc:1.20-trixie AS ldc-bootstrap-imported

###############
# build stage #
###############

FROM docker.io/debian:trixie-slim AS build-stage-2

WORKDIR /opt/build

# Install dependencies

## Install extended common system-tools

### Install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN apt-get -y install \
	build-essential \
	curl \
	git \
	libcurl4-openssl-dev
RUN rm -rf /var/lib/apt/lists/*

## Install LDC build deps
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
	cmake \
	ninja-build \
	python3
RUN rm -rf /var/lib/apt/lists/*

# Copy prebuilt LLVM from dlang-dockerized/llvm
COPY --from=llvm-imported /opt/llvm/ /opt/llvm/

# Download LDC sources

### Download LDC source
RUN curl -fLsSo ldc.tar.gz \
	"https://github.com/ldc-developers/ldc/archive/refs/tags/v1.41.0.tar.gz"

### Download Phobos source
RUN curl -fLsSo phobos.tar.gz \
	"https://github.com/ldc-developers/phobos/archive/refs/tags/ldc-v1.41.0.tar.gz"


# Copy prebuilt LDC from dlang-dockerized/ldc
COPY --from=ldc-bootstrap-imported /opt/ldc/ /opt/ldc-bootstrap/
RUN find /opt/ldc-bootstrap/etc/ldc2.conf -type f -exec sed -i 's/\/opt\/ldc/\/opt\/ldc-bootstrap/g' {} \;

# Build and install LDC

ENV DMD=/opt/ldc-bootstrap/bin/ldmd2
## Build LDC

### Unpack sources
RUN mkdir ldc-source ldc-build
RUN tar -xf ldc.tar.gz -C ldc-source --strip-components=1
RUN tar -xf phobos.tar.gz -C ldc-source/runtime/phobos --strip-components=1


### Build
RUN cmake \
	-S ldc-source \
	-B ldc-build \
	-G Ninja \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/opt/ldc \
	-DLLVM_ROOT_DIR=/opt/llvm \
	-DCMAKE_C_COMPILER=gcc \
	-DCMAKE_CXX_COMPILER=g++ \
	-DCMAKE_ASM_COMPILER=gcc
	#-DLDC_EXE=y # didn't work
RUN cmake --build ldc-build

### Install
RUN cmake --install ldc-build
ENV DMD=/opt/ldc/bin/ldmd2

# Self-test
COPY ./resources/helloworld.d /opt/helloworld.d
RUN /opt/ldc/bin/ldmd2 -run /opt/helloworld.d
RUN rm /opt/helloworld.d

##################
# self bootstrap #
##################

FROM docker.io/debian:trixie-slim AS build-stage-3

WORKDIR /opt/build

# Install dependencies

## Install extended common system-tools

### Install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN apt-get -y install \
	build-essential \
	curl \
	git \
	libcurl4-openssl-dev
RUN rm -rf /var/lib/apt/lists/*

## Install LDC build deps
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
	cmake \
	ninja-build \
	python3
RUN rm -rf /var/lib/apt/lists/*

# Copy prebuilt LLVM from dlang-dockerized/llvm
COPY --from=llvm-imported /opt/llvm/ /opt/llvm/

# Download LDC sources

### Download LDC source
RUN curl -fLsSo ldc.tar.gz \
	"https://github.com/ldc-developers/ldc/archive/refs/tags/v1.41.0.tar.gz"

### Download Phobos source
RUN curl -fLsSo phobos.tar.gz \
	"https://github.com/ldc-developers/phobos/archive/refs/tags/ldc-v1.41.0.tar.gz"


# Copy prebuilt LDC from dlang-dockerized/ldc
COPY --from=build-stage-2 /opt/ldc/ /opt/ldc-bootstrap/
RUN find /opt/ldc-bootstrap/etc/ldc2.conf -type f -exec sed -i 's/\/opt\/ldc/\/opt\/ldc-bootstrap/g' {} \;

# Build and install LDC

ENV DMD=/opt/ldc-bootstrap/bin/ldmd2
## Build LDC

### Unpack sources
RUN mkdir ldc-source ldc-build
RUN tar -xf ldc.tar.gz -C ldc-source --strip-components=1
RUN tar -xf phobos.tar.gz -C ldc-source/runtime/phobos --strip-components=1


### Build
RUN cmake \
	-S ldc-source \
	-B ldc-build \
	-G Ninja \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/opt/ldc \
	-DLLVM_ROOT_DIR=/opt/llvm \
	-DCMAKE_C_COMPILER=gcc \
	-DCMAKE_CXX_COMPILER=g++ \
	-DCMAKE_ASM_COMPILER=gcc
	#-DLDC_EXE=y # didn't work
RUN cmake --build ldc-build

### Install
RUN cmake --install ldc-build
ENV DMD=/opt/ldc/bin/ldmd2

# Self-test
COPY ./resources/helloworld.d /opt/helloworld.d
RUN /opt/ldc/bin/ldmd2 -run /opt/helloworld.d
RUN rm /opt/helloworld.d

## Make DUB

### Download, build and install DUB
## Download DUB source
RUN curl -fLsSo dub.tar.gz \
	"https://github.com/dlang/dub/archive/refs/tags/v1.40.0.tar.gz"

## Build DUB

### Unpack sources
RUN mkdir -p dub
RUN tar -xf dub.tar.gz -C dub --strip-components=1

### Patch build script
COPY resources/patches/wrap-std-process-execute.d wrap-std-process-execute.d
RUN cat wrap-std-process-execute.d >> dub/build.d

### Build
WORKDIR /opt/build/dub
RUN DFLAGS="-O2" \
	$DMD -run build.d
WORKDIR /opt/build


## Make D Tools

### Download D Tools source
RUN curl -fLsSo d-tools.tar.gz "https://github.com/dlang/tools/archive/refs/tags/v2.111.0.tar.gz"
### Build D Tools
RUN mkdir -p d-tools
RUN tar -xf d-tools.tar.gz -C d-tools --strip-components=1
RUN make -C d-tools \
	DMD=$DMD \
	all
################
# export stage #
################

FROM docker.io/debian:trixie-slim AS export-stage

## Prepare runtime-environment

### Install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
	build-essential \
	curl \
	"$(apt-cache search -n 'libpython3\.[0-9]+$' | sed 's/ .*//')" \
	"$(apt-cache search -n 'libedit[0-9]+$' | sed 's/ .*//')" \
	"$(apt-cache search -n 'libncurses[0-9]+$' | sed 's/ .*//')" \
	libcurl4-openssl-dev
RUN rm -rf /var/lib/apt/lists/*

COPY --from=llvm-imported /opt/llvm/bin /opt/llvm/bin

RUN ln -s /opt/llvm/bin/clang /usr/local/bin/clang
RUN ln -s /opt/llvm/bin/clang /usr/local/bin/clang++
RUN ln -s /opt/llvm/bin/llc /usr/local/bin/llc

RUN ln -s /opt/llvm/bin/lld /usr/local/bin/ld
RUN ln -s /opt/llvm/bin/lld /usr/local/bin/ld.lld
RUN ln -s /opt/llvm/bin/lld /usr/local/bin/lld
RUN ln -s /opt/llvm/bin/lld /usr/local/bin/lld-link

COPY --from=llvm-imported /opt/llvm/lib/liblldb.so* /opt/llvm/lib/
COPY --from=llvm-imported /opt/llvm/local/lib /opt/llvm/local/lib
RUN ln -s /opt/llvm/bin/lldb /usr/local/bin/lldb
RUN ln -s /opt/llvm/bin/lli /usr/local/bin/lli

COPY --from=build-stage-3 /opt/ldc /opt/ldc

RUN ln -s /opt/ldc/bin/ldc2 /usr/local/bin/ldc2
RUN ln -s /opt/ldc/bin/ldmd2 /usr/local/bin/ldmd2
RUN ln -s /opt/ldc/bin/ldmd2 /usr/local/bin/dmd
ENV DMD=/usr/local/bin/ldmd2

## Install D Tools
COPY --from=build-stage-3 /opt/build/d-tools/generated/linux/64/ddemangle /usr/local/bin/ddemangle
COPY --from=build-stage-3 /opt/build/d-tools/generated/linux/64/dustmite /usr/local/bin/dustmite
COPY --from=build-stage-3 /opt/build/d-tools/generated/linux/64/rdmd /usr/local/bin/rdmd
# Self-test
COPY ./resources/helloworld.d /opt/helloworld.d
RUN /opt/ldc/bin/ldmd2 -run /opt/helloworld.d
RUN rm /opt/helloworld.d

COPY --from=build-stage-3 /opt/build/dub/bin/dub /usr/local/bin/dub

## Install D Tools
COPY --from=build-stage-3 /opt/build/d-tools/generated/linux/64/ddemangle /usr/local/bin/ddemangle
COPY --from=build-stage-3 /opt/build/d-tools/generated/linux/64/dustmite /usr/local/bin/dustmite
COPY --from=build-stage-3 /opt/build/d-tools/generated/linux/64/rdmd /usr/local/bin/rdmd
COPY ./resources/scripts/entrypoint-ldc.sh /usr/local/bin/entrypoint

ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
CMD [ "/usr/local/bin/ldc2" ]
